In [5]:
import xarray as xr
import numpy as np
import pandas as pd

**The DataArray constructor takes:**

* data: a multi-dimensional array of values (e.g., a numpy ndarray, a numpy-like array, Series, DataFrame or pandas.Panel)
* coords: a list or dictionary of coordinates. If a list, it should be a list of tuples where the first element is the dimension name and the second element is the corresponding coordinate array_like object.
* dims: a list of dimension names. If omitted and coords is a list of tuples, dimension names are taken from coords.
* attrs: a dictionary of attributes to add to the instance
* name: a string that names the instance

In [6]:
data = np.random.rand(4, 3)

locs = ["IA", "IL", "IN"]

times = pd.date_range("2000-01-01", periods=4)

In [8]:
foo = xr.DataArray(data, coords=[times, locs], dims=["time", "space"])

print(foo)

<xarray.DataArray (time: 4, space: 3)>
array([[0.64230514, 0.19628534, 0.66744634],
       [0.6994205 , 0.42681539, 0.75576634],
       [0.32984206, 0.22904273, 0.08337776],
       [0.99637809, 0.58905771, 0.74861358]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'


In [10]:
bar = xr.DataArray(data)

print(bar)

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.64230514, 0.19628534, 0.66744634],
       [0.6994205 , 0.42681539, 0.75576634],
       [0.32984206, 0.22904273, 0.08337776],
       [0.99637809, 0.58905771, 0.74861358]])
Dimensions without coordinates: dim_0, dim_1


In [15]:
with_coords = xr.DataArray(data, coords=[("time", times), ("space", locs)])

print(with_coords)

<xarray.DataArray (time: 4, space: 3)>
array([[0.64230514, 0.19628534, 0.66744634],
       [0.6994205 , 0.42681539, 0.75576634],
       [0.32984206, 0.22904273, 0.08337776],
       [0.99637809, 0.58905771, 0.74861358]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'


In [16]:
coords_with_dict = xr.DataArray(
    data,
    coords={
        "time": times,
        "space": locs,
        "const": 42,
        "ranking": ("space", [1, 2, 3]),
    },
    dims=["time", "space"],
)

print(coords_with_dict)


<xarray.DataArray (time: 4, space: 3)>
array([[0.64230514, 0.19628534, 0.66744634],
       [0.6994205 , 0.42681539, 0.75576634],
       [0.32984206, 0.22904273, 0.08337776],
       [0.99637809, 0.58905771, 0.74861358]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    const    int64 42
    ranking  (space) int64 1 2 3
