In [21]:
import xarray as xr
import numpy as np
import pandas as pd

**The DataArray constructor takes:**

* data: a multi-dimensional array of values (e.g., a numpy ndarray, a numpy-like array, Series, DataFrame or pandas.Panel)
* coords: a list or dictionary of coordinates. If a list, it should be a list of tuples where the first element is the dimension name and the second element is the corresponding coordinate array_like object.
* dims: a list of dimension names. If omitted and coords is a list of tuples, dimension names are taken from coords.
* attrs: a dictionary of attributes to add to the instance
* name: a string that names the instance

In [22]:
data = np.random.rand(4, 3)

locs = ["IA", "IL", "IN"]

times = pd.date_range("2000-01-01", periods=4)

In [23]:
foo = xr.DataArray(data, coords=[times, locs], dims=["time", "space"])

print(foo)

<xarray.DataArray (time: 4, space: 3)>
array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'


In [24]:
bar = xr.DataArray(data)

print(bar)

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])
Dimensions without coordinates: dim_0, dim_1


In [25]:
with_coords = xr.DataArray(data, coords=[("time", times), ("space", locs)])

print(with_coords)

<xarray.DataArray (time: 4, space: 3)>
array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'


In [26]:
# Passing coords as a dictionary

coords_with_dict = xr.DataArray(
    data,
    coords={
        "time": times,
        "space": locs,
        "const": 42,
        "ranking": ("space", [1, 2, 3]),
    },
    dims=["time", "space"],
)

print(coords_with_dict)


<xarray.DataArray (time: 4, space: 3)>
array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    const    int64 42
    ranking  (space) int64 1 2 3


In [27]:
# Passing coords as a dictionary across multiple dimensions

xr.DataArray(
    data,
    coords={
        "time": times,
        "space": locs,
        "const": 42,
        "ranking": (("time", "space"), np.arange(12).reshape(4, 3)),
    },
    dims=["time", "space"],
)


<xarray.DataArray (time: 4, space: 3)>
array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    const    int64 42
    ranking  (time, space) int64 0 1 2 3 4 5 6 7 8 9 10 11

### DataArray properties

In [28]:
foo.values

array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])

In [29]:
foo.dims

('time', 'space')

In [30]:
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [31]:
foo.name

In [33]:
foo.values

array([[0.31448662, 0.09747849, 0.87795405],
       [0.34956513, 0.68957886, 0.2888144 ],
       [0.29223855, 0.87161492, 0.71254623],
       [0.60510639, 0.24750725, 0.54258971]])

In [37]:
foo.values = 2.0 * foo.values
print(foo.values)

[[0.62897325 0.19495698 1.75590811]
 [0.69913026 1.37915772 0.57762879]
 [0.5844771  1.74322984 1.42509246]
 [1.21021278 0.4950145  1.08517941]]


In [38]:
foo.name = "foo"

In [39]:
foo.attrs["units"] = "meters"

In [40]:
foo

<xarray.DataArray 'foo' (time: 4, space: 3)>
array([[0.62897325, 0.19495698, 1.75590811],
       [0.69913026, 1.37915772, 0.57762879],
       [0.5844771 , 1.74322984, 1.42509246],
       [1.21021278, 0.4950145 , 1.08517941]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Attributes:
    units:    meters

In [41]:
foo.rename("bar")

<xarray.DataArray 'bar' (time: 4, space: 3)>
array([[0.62897325, 0.19495698, 1.75590811],
       [0.69913026, 1.37915772, 0.57762879],
       [0.5844771 , 1.74322984, 1.42509246],
       [1.21021278, 0.4950145 , 1.08517941]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Attributes:
    units:    meters

In [44]:
foo.coords["time"]

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [46]:
foo["time"]


<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04